"""
Copyright (c) Meta Platforms, Inc. and affiliates.
All rights reserved.
This source code is licensed under the license found in the
LICENSE file in the root directory of this source tree.
"""
name_mappings = {
 'thomas burke': 'thomas burke',
 'fritz hofmann': 'fritz hofmann',
 'frank jarvis': 'frank jarvis',
 'walter tewksbury': 'walter tewksbury',
 'stan rowley': 'stan rowley',
 'stanley rowley': 'stan rowley',
 'archie hahn': 'archie hahn',
 'charles archibald hahn': 'archie hahn',
 'nathaniel cartmell': 'nathaniel cartmell',
 'nate cartmell': 'nathaniel cartmell',
 'nat cartmell': 'nathaniel cartmell',
 'nathaniel john cartmell': 'nathaniel cartmell',
 'william hogenson': 'william hogenson',
 'reggie walker': 'reggie walker',
 'reginalds walker': 'reggie walker',
 'reginald edgar walker': 'reggie walker',
 'james rector': 'james rector',
 'robert kerr': 'robert kerr',
 'ralph craig': 'ralph craig',
 'alvah meyer': 'alvah meyer',
 'donald lippincott': 'donald lippincott',
 'charley paddock': 'charley paddock',
 'charles paddock': 'charley paddock',
 'charles william paddock': 'charley paddock',
 'morris kirksey': 'morris kirksey',
 'harry edward': 'harry edward',
 'harold abrahams': 'harold abrahams',
 'jackson scholz': 'jackson scholz',
 'arthur porritt': 'arthur porritt',
 'baron porritt': 'arthur porritt',
 'arthur porrit baron porritt': 'arthur porritt',
 'percy williams': 'percy williams',
 'jack london': 'jack london',
 'georg lammers': 'georg lammers',
 'eddie tolan': 'eddie tolan',
 'thomas edward tolan': 'eddie tolan',
 'ralph metcalfe': 'ralph metcalfe',
 'arthur jonath': 'arthur jonath',
 'jesse owens': 'jesse owens',
 'james owens': 'jesse owens',
 'james cleveland owens': 'jesse owens',
 'tinus osendarp': 'tinus osendarp',
 'harrison dillard': 'harrison dillard',
 'barney ewell': 'barney ewell',
 'harold ewell': 'barney ewell',
 'harold norwood ewell': 'barney ewell',
 'lloyd labeach': 'lloyd labeach',
 'lindy remigino': 'lindy remigino',
 'herb mckenley': 'herb mckenley',
 'herbert mckenley': 'herb mckenley',
 'herbert henry mckenley': 'herb mckenley',
 'mcdonald bailey': 'mcdonald bailey',
 'bobby morrow': 'bobby morrow',
 'thane baker': 'thane baker',
 'walter thane baker': 'thane baker',
 'hector hogan': 'hector hogan',
 'armin hary': 'armin hary',
 'dave sime': 'dave sime',
 'david sime': 'dave sime',
 'david william sime': 'dave sime',
 'peter radford': 'peter radford',
 'bob hayes': 'bob hayes',
 'robert lee hayes': 'bob hayes',
 'enrique figueroa': 'enrique figueroa',
 'harry jerome': 'harry jerome',
 'jim hines': 'jim hines',
 'james hines': 'jim hines',
 'james ray hines': 'jim hines',
 'lennox miller': 'lennox miller',
 'charles greene': 'charles greene',
 'valeriy borzov': 'valeriy borzov',
 'robert taylor': 'robert taylor',
 'hasely crawford': 'hasely crawford',
 'don quarrie': 'don quarrie',
 'donald quarrie': 'don quarrie',
 'allan wells': 'allan wells',
 'silvio leonard': 'silvio leonard',
 'petar petrov': 'petar petrov',
 'carl lewis': 'carl lewis',
 'frederick carlton lewis': 'carl lewis',
 'sam graddy': 'sam graddy',
 'samuel graddy': 'sam graddy',
 'ben johnson': 'ben johnson',
 'benjamin johnson': 'ben johnson',
 'linford christie': 'linford christie',
 'calvin smith': 'calvin smith',
 'frankie fredericks': 'frankie fredericks',
 'frank fredericks': 'frankie fredericks',
 'dennis mitchell': 'dennis mitchell',
 'donovan bailey': 'donovan bailey',
 'ato boldon': 'ato boldon',
 'maurice greene': 'maurice greene',
 'obadele thompson': 'obadele thompson',
 'justin gatlin': 'justin gatlin',
 'francis obikwelu': 'francis obikwelu',
 'usain bolt': 'usain bolt',
 'richard thompson': 'richard thompson',
 'walter dix': 'walter dix',
 'yohan blake': 'yohan blake',
 'andre de grasse': 'andre de grasse',
 'marcell jacobs': 'marcell jacobs',
 'fred kerley': 'fred kerley',
 'frederick kerley': 'fred kerley',
 'betty robinson': 'betty robinson',
 'elizabeth robinson': 'betty robinson',
 'fanny rosenfeld': 'fanny rosenfeld',
 'ethel smith': 'ethel smith',
 'stanisława walasiewicz': 'stanisława walasiewicz',
 'stanislawa walasiewicz': 'stanisława walasiewicz',
 'hilda strike': 'hilda strike',
 'wilhelmina von bremen': 'wilhelmina von bremen',
 'helen stephens': 'helen stephens',
 'käthe krauß': 'käthe krauß',
 'fanny blankerskoen': 'fanny blankerskoen',
 'francina blankerskoen': 'fanny blankerskoen',
 'dorothy manley': 'dorothy manley',
 'shirley strickland': 'shirley strickland',
 'shirley strickland de la hunty': 'shirley strickland',
 'marjorie jackson': 'marjorie jackson',
 'daphne hasenjager': 'daphne hasenjager',
 'betty cuthbert': 'betty cuthbert',
 'elizabeth alyse cuthbert': 'betty cuthbert',
 'elizabeth cuthbert': 'betty cuthbert',
 'christa stubnick': 'christa stubnick',
 'marlene matthews': 'marlene matthews',
 'wilma rudolph': 'wilma rudolph',
 'dorothy hyman': 'dorothy hyman',
 'giuseppina leone': 'giuseppina leone',
 'wyomia tyus': 'wyomia tyus',
 'edith mcguire': 'edith mcguire',
 'ewa kłobukowska': 'ewa kłobukowska',
 'ewa klobukowska': 'ewa kłobukowska',
 'barbara ferrell': 'barbara ferrell',
 'irena szewinska': 'irena szewinska',
 'irena szewińska': 'irena szewinska',
 'renate stecher': 'renate stecher',
 'raelene boyle': 'raelene boyle',
 'silvia chivás': 'silvia chivás',
 'silvia chivas': 'silvia chivás',
 'annegret richter': 'annegret richter',
 'inge helten': 'inge helten',
 'lyudmila kondratyeva': 'lyudmila kondratyeva',
 'marlies göhr': 'marlies göhr',
 'ingrid auerswald': 'ingrid auerswald',
 'evelyn ashford': 'evelyn ashford',
 'alice brown': 'alice brown',
 'merlene ottey': 'merlene ottey',
 'florence griffithjoyner': 'florence griffithjoyner',
 'heike drechsler': 'heike drechsler',
 'gail devers': 'gail devers',
 'juliet cuthbert': 'juliet cuthbert',
 'irina privalova': 'irina privalova',
 'gwen torrence': 'gwen torrence',
 'merle ottey': 'merle ottey',
 'yulia nestsiarenka': 'yulia nestsiarenka',
 'lauryn williams': 'lauryn williams',
 'veronica campbell': 'veronica campbell',
 'shellyann fraser': 'shellyann fraser',
 'shellyann fraserpryce': 'shellyann fraser',
 'carmelita jeter': 'carmelita jeter',
 'veronica campbellbrown': 'veronica campbellbrown',
 'elaine thompson': 'elaine thompson',
 'elaine thompsonherah': 'elaine thompson',
 'tori browie': 'tori browie',
 'frentorish browie': 'tori browie',
 'shericka jackson': 'shericka jackson',
 'henri oreiller': 'henri oreiller',
 'franz gabl': 'franz gabl',
 'zeno colò': 'zeno colò',
 'zeno colo': 'zeno colò',
 'othmar schneider': 'othmar schneider',
 'christian pravda': 'christian pravda',
 'toni sailer': 'toni sailer',
 'anton seiler': 'toni sailer',
 'anton engelbert sailer': 'toni sailer',
 'raymond fellay': 'raymond fellay',
 'anderl molterer': 'anderl molterer',
 'andreas molterer': 'anderl molterer',
 'jean vuarnet': 'jean vuarnet',
 'hanspeter lanig': 'hanspeter lanig',
 'guy périllat': 'guy périllat',
 'egon zimmermann': 'egon zimmermann',
 'léo lacroix': 'léo lacroix',
 'wolfgang bartels': 'wolfgang bartels',
 'jeanclaude killy': 'jeanclaude killy',
 'jeandaniel dätwyler': 'jeandaniel dätwyler',
 'bernhard russi': 'bernhard russi',
 'roland collombin': 'roland collombin',
 'heinrich messner': 'heinrich messner',
 'franz klammer': 'franz klammer',
 'herbert plank': 'herbert plank',
 'leonhard stock': 'leonhard stock',
 'peter wirnsberger': 'peter wirnsberger',
 'steve podborski': 'steve podborski',
 'steven podborski': 'steve podborski',
 'steven gregory podborski': 'steve podborski',
 'bill johnson': 'bill johnson',
 'william johnson': 'bill johnson',
 'william dean johnson': 'bill johnson',
 'peter müller': 'peter müller',
 'anton steiner': 'anton steiner',
 'pirmin zurbriggen': 'pirmin zurbriggen',
 'franck piccard': 'franck piccard',
 'patrick ortlieb': 'patrick ortlieb',
 'günther mader': 'günther mader',
 'tommy moe': 'tommy moe',
 'thomas sven moe': 'tommy moe',
 'thomas moe': 'tommy moe',
 'kjetil andré aamodt': 'kjetil andré aamodt',
 'ed podivinsky': 'ed podivinsky',
 'edward charles podivinsky': 'ed podivinsky',
 'edward podivinsky': 'ed podivinsky',
 'jeanluc crétier': 'jeanluc crétier',
 'lasse kjus': 'lasse kjus',
 'hannes trinkl': 'hannes trinkl',
 'fritz strobl': 'fritz strobl',
 'stephan eberharter': 'stephan eberharter',
 'antoine dénériaz': 'antoine dénériaz',
 'michael walchhofer': 'michael walchhofer',
 'bruno kernen': 'bruno kernen',
 'didier défago': 'didier défago',
 'aksel lund svindal': 'aksel lund svindal',
 'bode miller': 'bode miller',
 'matthias mayer': 'matthias mayer',
 'christof innerhofer': 'christof innerhofer',
 'kjetil jansrud': 'kjetil jansrud',
 'beat feuz': 'beat feuz',
 'johan clarey': 'johan clarey',
 'hedy schlunegger': 'hedy schlunegger',
 'trude beiser': 'trude beiser',
 'resi hammerer': 'resi hammerer',
 'therese hammerer': 'resi hammerer',
 'trude jochumbeiser': 'trude jochumbeiser',
 'mirl buchner': 'mirl buchner',
 'giuliana minuzzo': 'giuliana minuzzo',
 'madeleine berthod': 'madeleine berthod',
 'frieda dänzer': 'frieda dänzer',
 'lucile wheeler': 'lucile wheeler',
 'heidi biebl': 'heidi biebl',
 'penelope pitou': 'penelope pitou',
 'traudl hecher': 'traudl hecher',
 'waltraud hecher': 'traudl hecher',
 'christl haas': 'christl haas',
 'edith zimmermann': 'edith zimmermann',
 'olga pall': 'olga pall',
 'isabelle mir': 'isabelle mir',
 'christa ulrike haas': 'christl haas',
 'christa haas': 'christl haas',
 'marietheres nadig': 'marietheres nadig',
 'annemarie moserpröll': 'annemarie moserpröll',
 'susan corrock': 'susan corrock',
 'rosi mittermaier': 'rosi mittermaier',
 'rosa mittermaier': 'rosi mittermaier',
 'rosa katharina mittermaier': 'rosi mittermaier',
 'brigitte totschnig': 'brigitte totschnig',
 'cindy nelson': 'cindy nelson',
 'hanni wenzel': 'hanni wenzel',
 'johanna wenzel': 'hanni wenzel',
 'michela figini': 'michela figini',
 'maria walliser': 'maria walliser',
 'olga charvátová': 'olga charvátová',
 'olga charvatova': 'olga charvátová',
 'marina kiehl': 'marina kiehl',
 'brigitte oertli': 'brigitte oertli',
 'karen percy': 'karen percy',
 'kerrin leegartner': 'kerrin leegartner',
 'hilary lindh': 'hilary lindh',
 'veronika wallinger': 'veronika wallinger',
 'katja seizinger': 'katja seizinger',
 'picabo street': 'picabo street',
 'isolde kostner': 'isolde kostner',
 'pernilla wiberg': 'pernilla wiberg',
 'florence masnada': 'florence masnada',
 'carole montillet': 'carole montillet',
 'renate götschl': 'renate götschl',
 'michaela dorfmeister': 'michaela dorfmeister',
 'martina schild': 'martina schild',
 'anja pärson': 'anja pärson',
 'lindsey vonn': 'lindsey vonn',
 'julia mancuso': 'julia mancuso',
 'elisabeth görgl': 'elisabeth görgl',
 'lara gut': 'lara gut',
 'sofia goggia': 'sofia goggia',
 'ragnhild mowinckel': 'ragnhild mowinckel',
 'corinne suter': 'corinne suter',
 'nadia delago': 'nadia delago'
}



city_mappings = {
 'bentonville': 'bentonville',
 'bentonville arkansas': 'bentonville',
 'bentonville ar': 'bentonville',
 'seattle': 'seattle',
 'seattle washington': 'seattle',
 'seattle wa': 'seattle',
 'spring': 'spring',
 'spring texas': 'spring',
 'spring tx': 'spring',
 'cupertino': 'cupertino',
 'cupertino california': 'cupertino',
 'cupertino ca': 'cupertino',
 'minnetonka': 'minnetonka',
 'minnetonka minnesota': 'minnetonka',
 'minnetonka mn': 'minnetonka',
 'woonsocket': 'woonsocket',
 'woonsocket rhode island': 'woonsocket',
 'woonsocket ri': 'woonsocket',
 'omaha': 'omaha',
 'omaha nebraska': 'omaha',
 'omaha ne': 'omaha',
 'mountain view': 'mountain view',
 'mountain view california': 'mountain view',
 'mountain view ca': 'mountain view',
 'irving': 'irving',
 'irving texas': 'irving',
 'irving tx': 'irving',
 'san ramon': 'san ramon',
 'san ramon california': 'san ramon',
 'san ramon ca': 'san ramon',
 'chesterbrook': 'chesterbrook',
 'chesterbrook pennsylvania': 'chesterbrook',
 'chesterbrook pa': 'chesterbrook',
 'issaquah': 'issaquah',
 'issaquah washington': 'issaquah',
 'issaquah wa': 'issaquah',
 'redmond': 'redmond',
 'redmond washington': 'redmond',
 'redmond wa': 'redmond',
 'dublin': 'dublin',
 'dublin ohio': 'dublin',
 'dublin oh': 'dublin',
 'bloomfield': 'bloomfield',
 'bloomfield connecticut': 'bloomfield',
 'bloomfield ct': 'bloomfield',
 'findlay': 'findlay',
 'findlay ohio': 'findlay',
 'findlay oh': 'findlay',
 'houston': 'houston',
 'houston texas': 'houston',
 'houston tx': 'houston',
 'san antonio': 'san antonio',
 'san antonio texas': 'san antonio',
 'san antonio tx': 'san antonio',
 'dearborn': 'dearborn',
 'dearborn michigan': 'dearborn',
 'dearborn mi': 'dearborn',
 'atlanta': 'atlanta',
 'atlanta georgia': 'atlanta',
 'atlanta ga': 'atlanta',
 'detroit': 'detroit',
 'detroit michigan': 'detroit',
 'detroit mi': 'detroit',
 'indianapolis': 'indianapolis',
 'indianapolis indiana': 'indianapolis',
 'indianapolis in': 'indianapolis',
 'new york': 'new york',
 'new york city new york': 'new york',
 'new york city ny': 'new york',
 'new york ny': 'new york',
 'new york city': 'new york',
 'cincinnati': 'cincinnati',
 'cincinnati ohio': 'cincinnati',
 'cincinnati oh': 'cincinnati',
 'st louis': 'st louis',
 'st louis missouri': 'st louis',
 'st louis mo': 'st louis',
 'deerfield': 'deerfield',
 'deerfield illinois': 'deerfield',
 'deerfield il': 'deerfield',
 'washington': 'washington',
 'washington dc': 'washington',
 'dc': 'washington',
 'philadelphia': 'philadelphia',
 'philadelphia pennsylvania': 'philadelphia',
 'philadelphia pa': 'philadelphia',
 'dallas': 'dallas',
 'dallas texas': 'dallas',
 'dallas tx': 'dallas',
 'menlo park': 'menlo park',
 'menlo park california': 'menlo park',
 'menlo park ca': 'menlo park',
 'charlotte': 'charlotte',
 'charlotte north carolina': 'charlotte',
 'charlotte nc': 'charlotte',
 'minneapolis': 'minneapolis',
 'minneapolis minnesota': 'minneapolis',
 'minneapolis mn': 'minneapolis',
 'round rock': 'round rock',
 'round rock texas': 'round rock',
 'round rock tx': 'round rock',
 'chicago': 'chicago',
 'chicago illinois': 'chicago',
 'chicago il': 'chicago',
 'mooresville': 'mooresville',
 'mooresville north carolina': 'mooresville',
 'mooresville nc': 'mooresville',
 'new brunswick': 'new brunswick',
 'new brunswick new jersey': 'new brunswick',
 'new brunswick nj': 'new brunswick',
 'memphis': 'memphis',
 'memphis tennessee': 'memphis',
 'memphis tn': 'memphis',
 'louisville': 'louisville',
 'louisville kentucky': 'louisville',
 'louisville kn': 'louisville',
 'bloomington': 'bloomington',
 'bloomington illinois': 'bloomington',
 'bloomington il': 'bloomington',
 'mclean': 'mclean',
 'mclean virginia': 'mclean',
 'mclean va': 'mclean',
 'purchase': 'purchase',
 'purchase new york': 'purchase',
 'purchase ny': 'purchase',
 'san francisco': 'san francisco',
 'san francisci': 'san francisco',
 'san francisco california': 'san francisco',
 'sf': 'san francisco',
 'san francisci ca': 'san francisco',
 'burbank': 'burbank',
 'burbank california': 'burbank',
 'burbank ca': 'burbank',
 'austin': 'austin',
 'austin texas': 'austin',
 'austin tx': 'austin',
 'boise': 'boise',
 'boise idaho': 'boise',
 'boise id': 'boise',
 'boston': 'boston',
 'boston massachusetts': 'boston',
 'boston ma': 'boston',
 'white plains': 'white plains',
 'white plains new york': 'white plains',
 'white plains ny': 'white plains',
 'arlington': 'arlington',
 'arlington county virginia': 'arlington',
 'arlington county': 'arlington',
 'arlington virginia': 'arlington',
 'arlington va': 'arlington',
 'arlington county va': 'arlington',
 'bethesda': 'bethesda',
 'bethesda maryland': 'bethesda',
 'bethesda md': 'bethesda',
 'santa clara': 'santa clara',
 'santa clara california': 'santa clara',
 'santa clara ca': 'santa clara',
 'palo alto': 'palo alto',
 'palo alto california': 'palo alto',
 'palo alto ca': 'palo alto',
 'clearwater': 'clearwater',
 'clearwater florida': 'clearwater',
 'clearwater fl': 'clearwater',
 'armonk': 'armonk',
 'armonk new york': 'armonk',
 'armonk ny': 'armonk',
 'nashville': 'nashville',
 'nashville tennessee': 'nashville',
 'nashville tn': 'nashville',
 'newark': 'newark',
 'newark new jersey': 'newark',
 'newark nj': 'newark',
 'kenilworth': 'kenilworth',
 'kenilworth new jersey': 'kenilworth',
 'kenilworth nj': 'kenilworth',
 'miami': 'miami',
 'miami florida': 'miami',
 'miami fl': 'miami',
 'lake bluff': 'lake bluff',
 'lake bluff illinois': 'lake bluff',
 'lake bluff il': 'lake bluff',
 'midland': 'midland',
 'midland michigan': 'midland',
 'midland mi': 'midland',
 'lakeland': 'lakeland',
 'lakeland florida': 'lakeland',
 'lakeland fl': 'lakeland',
 'stamford': 'stamford',
 'stamford connecticut': 'stamford',
 'stamford ct': 'stamford',
 'springdale': 'springdale',
 'springdale arkansas': 'springdale',
 'springdale ar': 'springdale',
 'moline': 'moline',
 'moline illinois': 'moline',
 'moline il': 'moline',
 'san jose': 'san jose',
 'san jose california': 'san jose',
 'san jose ca': 'san jose',
 'columbus': 'columbus',
 'columbus ohio': 'columbus',
 'columbus oh': 'columbus',
 'northfield': 'northfield',
 'northfield township': 'northfield',
 'northfield township cook county illinois': 'northfield',
 'framingham': 'framingham',
 'framingham massachusetts': 'framingham',
 'framingham ma': 'framingham',
 'mayfield village': 'mayfield village',
 'mayfield village ohio': 'mayfield village',
 'mayfield village oh': 'mayfield village',
 'fort worth': 'fort worth',
 'fort worth texas': 'fort worth',
 'fort worth tx': 'fort worth',
 'inver grove heights': 'inver grove heights',
 'inver grove heights minnesota': 'inver grove heights',
 'inver grove heights mn': 'inver grove heights',
 'richmond': 'richmond',
 'richmond virginia': 'richmond',
 'richmond va': 'richmond',
 'parsippanytroy hills': 'parsippanytroy hills',
 'parsippanytroy hills new jersey': 'parsippanytroy hills',
 'parsippanytroy hills nj': 'parsippanytroy hills',
 'beaverton': 'beaverton',
 'beaverton oregon': 'beaverton',
 'beaverton or': 'beaverton',
 'richfield': 'richfield',
 'richfield minnesota': 'richfield',
 'richfield mn': 'richfield',
 'waltham': 'waltham',
 'waltham massachusetts': 'waltham',
 'waltham ma': 'waltham',
 'san diego': 'san diego',
 'san diego california': 'san diego',
 'san diego ca': 'san diego',
 'wolfsburg': 'wolfsburg',
 'wulfsborg': 'wolfsburg',
 'volsburgo': 'wolfsburg',
 'stuttgart': 'stuttgart',
 'stoccarda': 'stuttgart',
 'münchen': 'münchen',
 'munich': 'münchen',
 'monaco di baviera': 'münchen',
 'monaco': 'münchen',
 'berlino': 'berlino',
 'berlin': 'berlino',
 'berlijn': 'berlino',
 'bonn': 'bonn',
 'bonna': 'bonn',
 'herzogenaurach': 'herzogenaurach',
 'leverkusen': 'leverkusen',
 'köln': 'köln',
 'cologne': 'köln',
 'keulen': 'köln',
 'colonia': 'köln',
 'ludwigshafen': 'ludwigshafen',
 'ludwigshafen am rhein': 'ludwigshafen',
 'frankfurt am main': 'frankfurt am main',
 'frankfurt': 'frankfurt am main',
 'francoforte': 'frankfurt am main',
 'francoforte sul meno': 'frankfurt am main',
 'frankfort aan de main': 'frankfurt am main',
 'frankfoort': 'frankfurt am main',
 'walldorf': 'walldorf',
 'hamburg': 'hamburg',
 'amburgo': 'hamburg',
 'bad homburg': 'bad homburg',
 'bad homburg vor der höhe': 'bad homburg',
 'friedrichshafen': 'friedrichshafen',
 'bochum': 'bochum',
 'neckarsulm': 'neckarsulm',
 'essen': 'essen',
 'grenzachwyhlen': 'grenzachwyhlen',
 'darmstadt': 'darmstadt',
 'mülheim an der ruhr': 'essen',
 'mühlheim': 'essen',
 'gütersloh': 'gütersloh',
 'ingelheim am rhein': 'ingelheim am rhein',
 'ingelheim': 'ingelheim am rhein',
 'karlsruhe': 'karlsruhe',
 'karelsrust': 'karlsruhe',
 'selm': 'selm',
 'böblingen': 'böblingen',
 'künzelsau': 'künzelsau',
 'ismaning': 'ismaning',
 'salzgitter': 'salzgitter',
 'düsseldorf': 'düsseldorf',
 'dusseldorf': 'düsseldorf',
 'dusseldorp': 'düsseldorf',
 'rüsselsheim': 'rüsselsheim',
 'rüsselsheim am main': 'rüsselsheim',
 'kirchdorf an der iller': 'kirchdorf an der iller',
 'kirchdorf': 'kirchdorf an der iller',
 'coburg': 'coburg',
 'coburgo': 'coburg',
 'oberkochen': 'oberkochen',
 'montabaur': 'montabaur',
 'blankenfeldemahlow': 'blankenfeldemahlow',
 'weinheim': 'weinheim',
 'melsungen': 'melsungen',
 'koblenz': 'koblenz',
 'coblenza': 'koblenz',
 'lippstadt': 'lippstadt',
 'oldenburg': 'oldenburg',
 'oldenburgo': 'oldenburg',
 'gräfelfing': 'gräfelfing',
 'pullach': 'pullach',
 'mannheim': 'mannheim',
 'schwalbach am taunus': 'schwalbach am taunus',
 'schwalbach': 'schwalbach am taunus',
 'nürnberg': 'nürnberg',
 'neurenberg': 'nürnberg',
 'norimberga': 'nürnberg',
 'nuremberg': 'nürnberg',
 'aachen': 'aachen',
 'aquisgrana': 'aachen',
 'aken': 'aachen',
 'aixlachapelle': 'aachen',
 'neutraubling': 'neutraubling',
 'veldhoven': 'veldhoven',
 'amsterdam': 'amsterdam',
 'amsterdamo': 'amsterdam',
 'hague': 'hague',
 'the hague': 'hague',
 'den haag': 'hague',
 'laia': 'hague',
 'laja': 'hague',
 'haag': 'hague',
 'rotterdam': 'rotterdam',
 'rdam': 'rotterdam',
 'leiden': 'leiden',
 'leida': 'leiden',
 'hoofddorp': 'hoofddorp',
 'eindhoven': 'eindhoven',
 'amstelveen': 'amstelveen',
 'zug': 'amstelveen',
 'delft': 'delft',
 'hilversum': 'hilversum',
 'heerlen': 'heerlen',
 'zaandam': 'zaandam',
 'alphen aan den rijn': 'alphen aan den rijn',
 'alphen': 'alphen aan den rijn',
 'alphen am rhein': 'alphen aan den rijn',
 'almere': 'almere',
 'venlo': 'venlo',
 'diemen': 'diemen',
 'utrecht': 'utrecht',
 'duiven': 'duiven',
 'schipholrijk': 'schipholrijk',
 'papendrecht': 'papendrecht',
 'rijssen': 'rijssen',
 'rijssenholten': 'rijssen',
 'haaksbergen': 'haaksbergen',
 'sevenum': 'sevenum',
 'leidschendam': 'leidschendam',
 'leidschendamvoorburg': 'leidschendam',
 'shertogenbosch': 'shertogenbosch',
 'herzogenbusch': 'shertogenbosch',
 'den bosch': 'shertogenbosch',
 'boscoducale': 'shertogenbosch',
 'heerenveen': 'heerenveen',
 'naarden': 'naarden',
 'veghel': 'veghel',
 'schiphol': 'schiphol',
 'arnhem': 'arnhem',
 'bunnik': 'bunnik',
 'enschede': 'enschede',
 'nieuwegein': 'nieuwegein',
 'deurne': 'deurne',
 'groenlo': 'groenlo',
 'hoofdorp': 'hoofdorp',
 'amersfoort': 'amersfoort',
 'breda': 'breda',
 'lochem': 'lochem',
 'groningen': 'groningen',
 'groninga': 'groningen',
 'södertälje': 'södertälje',
 'nacka': 'nacka',
 'naka': 'nacka',
 'stockholm': 'stockholm',
 'stokholma': 'stockholm',
 'stoccolma': 'stockholm',
 'gothenburg': 'gothenburg',
 'göteborg': 'gothenburg',
 'gotemburgo': 'gothenburg',
 'gotenburg': 'gothenburg',
 'helsinki': 'helsinki',
 'helsingfors': 'helsinki',
 'sundsvall': 'sundsvall',
 'lund': 'lund',
 'lunda': 'lund',
 'markaryd': 'markaryd',
 'trelleborg': 'trelleborg',
 'trelleborga': 'trelleborg',
 'trollhättan': 'trollhättan',
 'solna': 'solna',
 'malmö': 'malmö',
 'malmò': 'malmö',
 'toronto': 'toronto',
 'enköping': 'enköping',
 'förslöv': 'förslöv',
 'västra frölunda': 'västra frölunda',
 'karlstad': 'karlstad',
 'luleå': 'luleå',
 'lūleo': 'luleå',
 'danderyd': 'danderyd',
 'helsingborg': 'helsingborg',
 'torekov': 'torekov',
 'rom': 'rom',
 'roma': 'rom',
 'rome': 'rom',
 'maranello': 'maranello',
 'torino': 'torino',
 'turin': 'torino',
 'turijn': 'torino',
 'milano': 'milano',
 'mailand': 'milano',
 'milaan': 'milano',
 'milan': 'milano',
 'triest': 'triest',
 'trieste': 'triest',
 'triëst': 'triest',
 'san donato milanese': 'san donato milanese',
 'san donato': 'san donato milanese',
 'sesto san giovanni': 'sesto san giovanni',
 'bologna': 'bologna',
 'bologne': 'bologna',
 'verona': 'milano',
 'basiglio': 'basiglio',
 'ellera di corciano': 'ellera di corciano',
 'santilario denza': 'santilario denza',
 'saluggia': 'saluggia',
 'brescia': 'milano',
 'stezzano': 'stezzano',
 'casale monferrato': 'casale monferrato',
 'casal': 'casale monferrato',
 'genova': 'genova',
 'genua': 'genova',
 'genoa': 'genova',
 'modena': 'modena',
 'siena': 'siena',
 'sienna': 'siena',
 'siëna': 'siena',
 'cologno monzese': 'cologno monzese',
 'treviso': 'treviso',
 'rozzano': 'rozzano',
 'brugine': 'brugine',
 'firenze': 'firenze',
 'florenz': 'firenze',
 'florens': 'firenze',
 'florence': 'firenze',
 'monza': 'monza',
 'reggio emilia': 'reggio emilia',
 'reggio nellemilia': 'reggio emilia',
 'reggio': 'reggio emilia',
 'sondrio': 'sondrio',
 'sünders': 'sondrio',
 'sonders': 'sondrio',
 'empoli': 'empoli',
 'cesena': 'cesena',
 'buttrio': 'buttrio',
 'santelpidio a mare': 'santelpidio a mare',
 'santelpidio': 'santelpidio a mare',
 'fossalta di portogruaro': 'fossalta di portogruaro',
 'fossalta': 'fossalta di portogruaro',
 'pontedera': 'pontedera',
 'ameglia': 'ameglia',
 'sarroch': 'sarroch',
 'rimini': 'rimini',
 'zola predosa': 'zola predosa',
 'reggiolo': 'reggiolo',
 'venezia': 'venezia',
 'venice': 'venezia',
 'venedig': 'venezia',
 'venetië': 'venezia',
 'jolanda di savoia': 'jolanda di savoia',
 'jolanda': 'jolanda di savoia',
 'varese': 'varese',
 'arezzo': 'arezzo',
 'pisa': 'pisa',
 'padua': 'padua',
 'padova': 'padua',
 'padoa': 'padua',
 'pieve di soligo': 'pieve di soligo',
 'pieve': 'pieve di soligo'
}
